"""
OpenRent Integration - Task 4: openrent_mapper.to_property_listing turns a
parsed-detail dict + (id, search_lat, search_lng) into a valid PropertyListing.
"""

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from homehunt.scrapers.openrent_extract import extract_detail
from homehunt.scrapers.openrent_mapper import to_property_listing
from homehunt.core.models import Portal


def main() -> int:
    fx = sorted((PROJECT_ROOT / "experiments" / "openrent-probe" / "fixtures").glob("detail-*.html"))[0]
    pid = int(fx.stem.split("-")[1])
    parsed = extract_detail(fx.read_text())
    listing = to_property_listing(
        parsed=parsed,
        property_id=pid,
        search_lat=51.5072,
        search_lng=-0.1276,
    )
    # Identity
    assert listing.portal == Portal.OPENRENT, f"portal={listing.portal}"
    assert listing.property_id == str(pid), f"property_id={listing.property_id}"
    assert listing.url == f"https://www.openrent.co.uk/{pid}", f"url={listing.url}"
    # uid uses the project convention "portal:property_id" (auto-generated by validator)
    assert listing.uid == f"openrent:{pid}", f"uid={listing.uid}"
    # Geo
    assert listing.area is not None, "area (postcode_area) must be set"
    assert listing.latitude == 51.5072
    assert listing.longitude == -0.1276
    # Price: raw string preserved, price_numeric auto-computed in PENCE
    assert listing.price is not None and "£" in listing.price, f"price={listing.price!r}"
    assert listing.price_numeric is not None and listing.price_numeric > 100_000, (
        f"price_numeric={listing.price_numeric} (must be > 100000 pence = £1000)"
    )
    # Spec
    assert listing.bedrooms is not None, "bedrooms missing"
    # Furnishing field renamed from furnishing -> furnished
    assert listing.furnished is not None, "furnished missing"
    # Images is a list[str]
    assert isinstance(listing.images, list), f"images type={type(listing.images).__name__}"
    print(
        f"PASS - mapper produced PropertyListing uid={listing.uid} "
        f"price_numeric={listing.price_numeric}p beds={listing.bedrooms} area={listing.area} "
        f"images={len(listing.images)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
