"""
Region resolution for rental-engine listings.

Resolves a (latitude, longitude) pair to the nearest verified neighbourhood
centroid name. Distance is unbounded: the geographic catchment is constrained
upstream by the Rightmove search radius, so any listing returned by the scrape
is by definition within the intended search area and gets a neighbourhood
label by nearest centroid.

Centroid data lives in data/neighbourhood_centroids.json, generated by
scripts/build_centroids.py from tiers.yaml via postcodes.io.
"""

import json
import math
import os
from functools import lru_cache

# Earth radius in miles (mean spherical radius)
_EARTH_RADIUS_MILES = 3958.8


def _haversine_miles(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """
    Compute the great-circle distance in miles between two points using
    the Haversine formula.

    Args:
        lat1, lon1: Origin point in decimal degrees.
        lat2, lon2: Destination point in decimal degrees.

    Returns:
        Distance in miles (float).
    """
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)

    a = (
        math.sin(dphi / 2.0) ** 2
        + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2.0) ** 2
    )
    return 2.0 * _EARTH_RADIUS_MILES * math.asin(math.sqrt(a))


@lru_cache(maxsize=1)
def _load_centroids() -> dict:
    """
    Load neighbourhood centroids from data/neighbourhood_centroids.json.

    Returns a dict mapping neighbourhood name to {"lat": float, "lng": float}.
    Result is cached for the lifetime of the process.
    """
    data_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "data",
        "neighbourhood_centroids.json",
    )
    with open(data_path) as f:
        return json.load(f)


def resolve_region(latitude: float, longitude: float) -> str:
    """
    Resolve a listing's (latitude, longitude) to the nearest verified
    neighbourhood name from the centroid set.

    No distance threshold is applied: the Rightmove search radius constrains
    the geography upstream, and any listing that arrives here is treated as
    in-catchment and gets a neighbourhood label by nearest centroid.

    Args:
        latitude:  Listing latitude in decimal degrees.
        longitude: Listing longitude in decimal degrees.

    Returns:
        Neighbourhood name string (exactly as it appears in tiers.yaml).
    """
    centroids = _load_centroids()

    best_name = ""
    best_dist = float("inf")

    for name, coords in centroids.items():
        dist = _haversine_miles(coords["lat"], coords["lng"], latitude, longitude)
        if dist < best_dist:
            best_dist = dist
            best_name = name

    return best_name
