#!/usr/bin/env python
"""Evaluate the production score against the sift v1 labelled set.

Joins sift labels (from /tmp/sift_v1_active.db) to the freshly-scored
listings in production (data/homehunt.db) and reports:
    - Spearman rank correlation between user tier and production score
    - Per-tier mean score (target: monotonic decline best -> worse)
    - Top-K disagreement cases

Output is printed to stdout and written to docs/sift_v1/2026-05-10-calibration-evaluation.md.
"""

from __future__ import annotations

import json
import os
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from scipy.stats import spearmanr

SIFT_DB = os.environ.get("SIFT_DB", "/tmp/sift_v1_active.db")
PROD_DB = os.environ.get("PROD_DB", str(PROJECT_ROOT / "data" / "homehunt.db"))
REPORT_PATH = PROJECT_ROOT / "docs" / "sift_v1" / "2026-05-10-calibration-evaluation.md"

TIER_RANK = {"best": 4, "good": 3, "bad": 2, "worse": 1}
TIER_ORDER = ["best", "good", "bad", "worse"]


def load_sift_labels() -> list[dict]:
    con = sqlite3.connect(SIFT_DB)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        """
        SELECT uid, tier, reasoning
        FROM sifting_label_v2
        WHERE session_id = (SELECT MAX(id) FROM sifting_session_v2)
        """
    ).fetchall()
    con.close()
    return [dict(r) for r in rows]


def load_production_scores(uids: list[str]) -> dict[str, dict]:
    con = sqlite3.connect(PROD_DB)
    con.row_factory = sqlite3.Row
    placeholders = ",".join("?" for _ in uids)
    rows = con.execute(
        f"""
        SELECT uid, score, score_breakdown, area, bedrooms,
               bedrooms_with_carpet, has_living_area_carpet
        FROM listing
        WHERE uid IN ({placeholders})
        """,
        uids,
    ).fetchall()
    con.close()
    return {r["uid"]: dict(r) for r in rows}


def main() -> None:
    labels = load_sift_labels()
    print(f"Loaded {len(labels)} sift labels from {SIFT_DB}")

    by_uid = load_production_scores([l["uid"] for l in labels])
    print(f"Joined {len(by_uid)} listings from {PROD_DB}")

    rows = []
    for label in labels:
        uid = label["uid"]
        prod = by_uid.get(uid)
        if prod is None:
            continue
        rows.append({
            "uid": uid,
            "tier": label["tier"],
            "tier_rank": TIER_RANK[label["tier"]],
            "score": prod["score"],
            "breakdown": json.loads(prod["score_breakdown"]) if prod["score_breakdown"] else {},
            "area": prod["area"],
            "reasoning": label["reasoning"],
            "bedrooms_with_carpet": prod["bedrooms_with_carpet"],
            "has_living_area_carpet": prod["has_living_area_carpet"],
        })

    print(f"Evaluable: {len(rows)} (joined and scored)")

    if len(rows) < 2:
        print("Not enough rows to compute correlation")
        return

    tier_ranks = [r["tier_rank"] for r in rows]
    scores = [r["score"] for r in rows]
    rho, p = spearmanr(tier_ranks, scores)
    rho = round(float(rho), 3)
    p = round(float(p), 4)

    by_tier: dict[str, list[int]] = defaultdict(list)
    for r in rows:
        by_tier[r["tier"]].append(r["score"])

    overrated = sorted(
        [r for r in rows if r["tier"] in ("bad", "worse")],
        key=lambda x: -x["score"],
    )[:6]
    underrated = sorted(
        [r for r in rows if r["tier"] in ("best", "good")],
        key=lambda x: x["score"],
    )[:6]

    lines: list[str] = []
    lines.append("# Sift v1 calibration evaluation")
    lines.append("")
    lines.append("**Date:** 2026-05-10. Generated by `scripts/sift_v1_evaluate_calibration.py`.")
    lines.append("")
    lines.append("## Headline")
    lines.append("")
    lines.append(f"- Spearman rank correlation (user tier vs new score): **{rho}** (p={p})")
    lines.append(f"- Baseline (pre-calibration, 2026-05-10): -0.165")
    lines.append("")
    lines.append("## Per-tier mean score")
    lines.append("")
    lines.append("| tier | n | mean score |")
    lines.append("|---|---|---|")
    for tier in TIER_ORDER:
        ss = by_tier.get(tier, [])
        if not ss:
            lines.append(f"| {tier} | 0 | - |")
            continue
        lines.append(f"| {tier} | {len(ss)} | {round(sum(ss)/len(ss), 1)} |")
    lines.append("")

    lines.append("## Highest-scored listings the user labelled bad / worse (over-rated)")
    lines.append("")
    lines.append("| uid | tier | score | bwc | liv | reasoning |")
    lines.append("|---|---|---|---|---|---|")
    for r in overrated:
        lines.append(
            f"| `{r['uid']}` | {r['tier']} | {r['score']} | "
            f"{r['bedrooms_with_carpet']} | {r['has_living_area_carpet']} | "
            f"{(r['reasoning'] or '').strip()} |"
        )
    lines.append("")
    lines.append("## Lowest-scored listings the user labelled best / good (under-rated)")
    lines.append("")
    lines.append("| uid | tier | score | bwc | liv | reasoning |")
    lines.append("|---|---|---|---|---|---|")
    for r in underrated:
        lines.append(
            f"| `{r['uid']}` | {r['tier']} | {r['score']} | "
            f"{r['bedrooms_with_carpet']} | {r['has_living_area_carpet']} | "
            f"{(r['reasoning'] or '').strip()} |"
        )
    lines.append("")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines))
    print(f"Report written to {REPORT_PATH}")
    print(f"Spearman rho = {rho} (was -0.165 pre-calibration)")
    print()
    for tier in TIER_ORDER:
        ss = by_tier.get(tier, [])
        if ss:
            print(f"  {tier:6s} n={len(ss):2d} mean={round(sum(ss)/len(ss), 1)}")


if __name__ == "__main__":
    main()
