#!/usr/bin/env python
"""Run the qwen3:4b theme-clustering pass over the sift v1 labelled reasonings.

Pulls reasoning text from /tmp/sift_v1_active.db, groups by tier, sends to
local Ollama (qwen3:4b in thinking mode), saves the structured markdown
response to docs/sift_v1/2026-05-10-sift-v1-themes.md.
"""

from __future__ import annotations

import json
import os
import sqlite3
from pathlib import Path

import urllib.request

DB_PATH = os.environ.get("SIFT_DB", "/tmp/sift_v1_active.db")
OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://127.0.0.1:11434/api/generate")
MODEL = os.environ.get("MODEL", "qwen3:4b")
PROJECT_ROOT = Path(__file__).resolve().parent.parent
REPORT_PATH = PROJECT_ROOT / "docs" / "sift_v1" / "2026-05-10-sift-v1-themes.md"

TIER_ORDER = ["best", "good", "bad", "worse"]


def load_reasonings_by_tier() -> dict[str, list[str]]:
    con = sqlite3.connect(DB_PATH)
    cur = con.execute(
        """
        SELECT tier, reasoning
        FROM sifting_label_v2
        WHERE session_id = (SELECT MAX(id) FROM sifting_session_v2)
          AND reasoning IS NOT NULL
          AND TRIM(reasoning) <> ''
        ORDER BY tier, position
        """
    )
    out: dict[str, list[str]] = {t: [] for t in TIER_ORDER}
    for tier, reasoning in cur.fetchall():
        out.setdefault(tier, []).append(reasoning.strip())
    con.close()
    return out


def build_prompt(by_tier: dict[str, list[str]]) -> str:
    blocks: list[str] = []
    for tier in TIER_ORDER:
        items = by_tier.get(tier, [])
        if not items:
            continue
        blocks.append(f"## {tier.upper()} ({len(items)} listings)")
        for r in items:
            blocks.append(f"- {r}")
        blocks.append("")
    listings_block = "\n".join(blocks)

    instruction = (
        "Analyse a London flat-hunter's labelled notes (4 tiers: BEST, GOOD, BAD, WORSE). "
        "Extract the structure of their preference function.\n\n"
        "OUTPUT RULES:\n"
        "- Output ONLY the final markdown report. No preamble, no 'let me think', no chain-of-thought.\n"
        "- Use the exact section headings below.\n"
        "- Be terse. Bullets only. Each bullet under 20 words.\n"
        "- Do not invent things the user did not say.\n"
        "- Do not narrate your counting. Just state the count.\n\n"
        "REPORT FORMAT:\n\n"
        "## Recurring themes per tier\n"
        "For each tier, the 3-5 dominant themes with count. Format: `- theme_name (n=X)`.\n\n"
        "## Cross-tier themes\n"
        "Themes appearing in 2+ tiers. For each: which tiers, and the user's rule that flips "
        "it from acceptable to rejecting. One sentence each.\n\n"
        "## Missing score components\n"
        "Dimensions the user judges on that a price+size+EPC+transport+carpet score does not "
        "capture. For each: snake_case_name | one-line definition | likely data source "
        "(description NLP / photo vision / floorplan vision / scraped photo count / etc).\n\n"
        "## Hard-reject signals\n"
        "Things treated as deal-breakers regardless of other qualities. One bullet each.\n\n"
        "## Forgivable trade-offs\n"
        "Negatives the user accepts when other qualities are strong. Quote the specific user "
        "phrase. One bullet each.\n\n"
        "## Vocabulary\n"
        "10-15 distinctive content words with the tier(s) they appear in. Format: "
        "`- word (tiers: best, bad)`.\n\n"
        "DATA:\n\n" + listings_block
    )
    return instruction


def call_ollama(prompt: str) -> str:
    payload = {
        "model": MODEL,
        "prompt": prompt,
        "stream": False,
        "think": False,
        "options": {
            "temperature": 0.2,
            "num_ctx": 8192,
            "num_predict": 4096,
        },
    }
    req = urllib.request.Request(
        OLLAMA_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=600) as resp:
        body = resp.read().decode("utf-8")
    parsed = json.loads(body)
    return parsed.get("response", "")


def main() -> None:
    by_tier = load_reasonings_by_tier()
    total = sum(len(v) for v in by_tier.values())
    print(f"Loaded {total} reasonings across {len(by_tier)} tiers")

    prompt = build_prompt(by_tier)
    print(f"Prompt length: {len(prompt)} chars")

    print(f"Calling {MODEL} ...")
    response = call_ollama(prompt)
    print(f"Response length: {len(response)} chars")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Sift v1 theme analysis\n\n"
        "**Date:** 2026-05-10. Generated by `scripts/sift_v1_theme_pass.py` "
        f"using `{MODEL}` (thinking mode) on local Ollama.\n\n"
        f"Source: 41 reasonings from sift session 1 at `/tmp/sift_v1_active.db`.\n\n"
        "---\n\n"
    )
    REPORT_PATH.write_text(header + response.strip() + "\n")
    print(f"Report written to {REPORT_PATH}")


if __name__ == "__main__":
    main()
