"""
EPC address-match threshold sweep.

Reads a hand-labelled CSV of EPC address match attempts, sweeps
rapidfuzz token_set_ratio threshold from lo to hi, and reports
precision/recall at each step.

CSV format (required columns):
  listing_address   str   scraped Rightmove address
  epc_address       str   concatenated EPC address1+address2+address3
  score             float token_set_ratio score (0.0 to 1.0 or 0 to 100)
  label             int   1 = correct match, 0 = false positive

The CSV can be generated by running the EPC enrichment pipeline in
audit mode and having a human verify each match decision.

Usage:
  python scripts/sweep_epc_threshold.py [--csv <path>] [--lo 0.4] [--hi 0.8]

The best threshold (maximising precision) is printed and written to
  homehunt/epc_threshold.py
so epc.py can read it at import time.
"""

import argparse
import csv
import os
import sys
from typing import Optional

# Normalise scores from 0-100 range (rapidfuzz default) to 0.0-1.0 range.
_SCORE_SCALE = 100.0


def load_labelled_csv(path: str) -> list[dict]:
    """Load a labelled CSV and return list of row dicts."""
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows


def sweep_thresholds(
    csv_path: str,
    lo: float = 0.4,
    hi: float = 0.8,
    step: float = 0.05,
) -> list[dict]:
    """
    Sweep token_set_ratio threshold from lo to hi (inclusive) in step increments.

    Scores in the CSV may be stored in 0.0-1.0 or 0-100 scale.  Values > 1.0
    are normalised to the 0.0-1.0 range by dividing by 100.

    Parameters
    ----------
    csv_path : str
        Path to the labelled CSV.
    lo : float
        Lowest threshold (inclusive).
    hi : float
        Highest threshold (inclusive).
    step : float
        Step between thresholds.

    Returns
    -------
    list of dicts with keys:
        threshold, tp, fp, fn, precision, recall
    """
    rows = load_labelled_csv(csv_path)

    # Parse and normalise scores and labels.
    parsed: list[tuple[float, int]] = []
    for row in rows:
        score = float(row["score"])
        label = int(row["label"])
        if score > 1.0:
            score = score / _SCORE_SCALE
        parsed.append((score, label))

    total_positives = sum(1 for _, lbl in parsed if lbl == 1)

    results = []
    threshold = lo
    while threshold <= hi + 1e-9:
        tp = 0
        fp = 0
        fn = 0
        for score, label in parsed:
            if score >= threshold:
                if label == 1:
                    tp += 1
                else:
                    fp += 1
            else:
                if label == 1:
                    fn += 1

        precision: Optional[float] = None
        if tp + fp > 0:
            precision = tp / (tp + fp)

        recall: Optional[float] = None
        if total_positives > 0:
            recall = tp / total_positives

        results.append(
            {
                "threshold": round(threshold, 4),
                "tp": tp,
                "fp": fp,
                "fn": fn,
                "precision": precision,
                "recall": recall,
            }
        )
        threshold = round(threshold + step, 4)

    return results


def best_precision_threshold(results: list[dict]) -> dict:
    """
    Return the result entry with the highest precision.

    When multiple entries tie on precision, return the one with the lowest
    threshold (highest recall at same precision).
    """
    eligible = [r for r in results if r["precision"] is not None]
    if not eligible:
        return results[-1]  # fallback to highest threshold
    return max(eligible, key=lambda r: (r["precision"], -(r["threshold"])))


def print_table(results: list[dict]) -> None:
    """Print a human-readable precision/recall table."""
    header = f"{'threshold':>10} {'tp':>6} {'fp':>6} {'fn':>6} {'precision':>10} {'recall':>10}"
    print(header)
    print("-" * len(header))
    for r in results:
        prec = f"{r['precision']:.4f}" if r["precision"] is not None else "  N/A  "
        rec = f"{r['recall']:.4f}" if r["recall"] is not None else "  N/A  "
        print(f"  {r['threshold']:>8.4f} {r['tp']:>6} {r['fp']:>6} {r['fn']:>6} {prec:>10} {rec:>10}")


def write_threshold_module(threshold: float, project_root: str) -> None:
    """Write the chosen threshold to homehunt/epc_threshold.py."""
    path = os.path.join(project_root, "homehunt", "epc_threshold.py")
    content = (
        '"""EPC address-match threshold -- generated by sweep_epc_threshold.py."""\n\n'
        f"EPC_MATCH_THRESHOLD: float = {threshold}\n"
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Threshold written to {path}")


# ---------------------------------------------------------------------------
# CLI entrypoint
# ---------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(description="Sweep EPC match threshold.")
    parser.add_argument(
        "--csv",
        default=os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "tests",
            "fixtures",
            "epc_match_labels.csv",
        ),
        help="Path to labelled CSV",
    )
    parser.add_argument("--lo", type=float, default=0.4, help="Lower bound")
    parser.add_argument("--hi", type=float, default=0.8, help="Upper bound")
    parser.add_argument("--step", type=float, default=0.05, help="Step size")
    args = parser.parse_args(argv)

    if not os.path.exists(args.csv):
        print(f"ERROR: CSV not found at {args.csv}")
        print("Build the labelled set with: python scripts/build_epc_labels.py")
        sys.exit(1)

    results = sweep_thresholds(args.csv, lo=args.lo, hi=args.hi, step=args.step)
    print_table(results)

    best = best_precision_threshold(results)
    rec_str = f"{best['recall']:.4f}" if best["recall"] is not None else "N/A"
    print(f"\nBest threshold (max precision): {best['threshold']:.4f}  "
          f"precision={best['precision']:.4f}  recall={rec_str}")

    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    write_threshold_module(best["threshold"], project_root)


if __name__ == "__main__":
    main()
